### ISSUE TITLE
Odroid H4 Support

### ISSUE THREAD

**Issue by dia3olik** [hominoids/Cloudshell4_Unauthorized#1]
Hey Ed!

Please consider adding Odroid H4 line support! ;-)

Thanks!!

**Comment by hominoids** [comment]
I have added two cases for the H4/H4+/H4 Ultra, the Cloudshell4 and Cloudshell4-XL.  See the related forum post for more details. https://forum.odroid.com/viewtopic.php?f=172&t=46383&start=1
I'm closing this issue but reopen it if you have any problems with the cases.  If you do try either of these I would appreciate some feedback since I don't own a H4.
